name: Build, Test, and Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Test on Python 3.8 - 3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Clean previous builds
        run: |
          if exist build rmdir /s /q build
          if exist dist rmdir /s /q dist
          if exist mouse_anywhere.egg-info rmdir /s /q mouse_anywhere.egg-info
        shell: cmd

      - name: Setup MSVC environment and compile C code
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath > vcpath.txt
          set /p vcpath=<vcpath.txt
          call "%vcpath%\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /LD mouse-anywhere.c /Fe:mouse_anywhere2.dll user32.lib

      - name: Verify DLL creation
        shell: cmd
        run: |
          if not exist mouse_anywhere2.dll (
            echo "DLL was not created."
            exit 1
          )
          echo "DLL successfully created."
          dir mouse_anywhere2.dll

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Verify dist contents
        run: |
          echo "Checking dist directory contents:"
          dir dist
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-python-package-${{ matrix.python-version }}
          path: dist/**/*

      - name: Run tests on Python ${{ matrix.python-version }}
        run: |
          REM Install the built package
          for %%f in (dist\*.whl) do pip install %%f || exit 1
          REM Install testing dependencies
          pip install pytest
          REM Run tests
          pytest tests/
        shell: cmd

  publish:
    needs: build
    runs-on: windows-latest
    if: >
      ${{ 
        (github.event_name == 'release' && github.event.action == 'published') ||
        (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
      }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-python-package-${{ matrix.python-version }}
          path: dist

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Publish from a single Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI with Twine
        run: |
          python -m twine upload dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
